stages:
  - build
  - deploy

variables:
  CONTAINER_RELEASE_IMAGE: $IMAGE_DOCKER:$CI_COMMIT_TAG


build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  script:
    - apk update && apk add git
    - apk add go
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf https://gitlab.com/
    - go env -w GOPRIVATE=gitlab.com/${CI_PROJECT_NAMESPACE}
    - go mod vendor
    - docker login -u "${USER_DOCKER}" -p "${PASSWORD_DOCKER}"
    - docker build --pull -t "$CONTAINER_RELEASE_IMAGE" .
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - tags
  except:
    - branches


pages:
  image: node:lts-gallium 
  stage: deploy
  script:
  - npm install -g redoc-cli
  - redoc-cli build -o public/index.html docs/web_deploy/openapi.yaml
  artifacts:
    paths:
    - public
  only:
  - main