image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - apk update && apk add git
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf https://gitlab.com/

format:
  image: golang:latest
  stage: test
  script:
    - go env -w GOPRIVATE=gitlab.com/${CI_PROJECT_NAMESPACE}
    - go mod vendor


build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - feature/docker-image

pages:
  image: node:latest
  stage: deploy
  script:
  - npm install -g redoc-cli
  - redoc-cli build -o public/index.html docs/web_deploy/openapi.yaml
  artifacts:
    paths:
    - public
  only:
  - main